let user,currentPage='home',currentCat=null,currentFolder=null;
document.addEventListener('DOMContentLoaded',()=>{if(!localStorage.getItem('token'))return location.href='/';user=JSON.parse(localStorage.getItem('user'));document.getElementById('userName').textContent=user.displayName;const b=document.getElementById('userRole');b.textContent=user.role.toUpperCase();if(user.role==='admin'){b.classList.add('admin');document.body.classList.add('is-admin')}document.querySelectorAll('[data-page]').forEach(el=>el.onclick=e=>{e.preventDefault();goPage(el.dataset.page)});initForms();loadData()});
function goPage(p){currentPage=p;document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===p));document.querySelectorAll('.page').forEach(pg=>pg.classList.toggle('active',pg.id===p+'Page'));if(p==='home')loadUpdates();if(p==='learning')loadLearning();document.getElementById('navMenu').classList.remove('show')}
function logout(){localStorage.clear();location.href='/'}
function openModal(id){document.getElementById(id).classList.add('show')}
function closeModal(id){document.getElementById(id).classList.remove('show')}
function toast(msg,ok){const t=document.getElementById('toast');t.className='toast'+(ok?' success':'');document.getElementById('toastMsg').textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
async function api(url,method='GET',body=null){const opts={method,headers:{'Content-Type':'application/json','Authorization':'Bearer '+localStorage.getItem('token')}};if(body)opts.body=JSON.stringify(body);const res=await fetch('/api/'+url,opts);return res.json()}
async function loadData(){await loadCategories();loadUpdates()}
async function loadUpdates(){const d=await api('updates');const c=document.getElementById('updatesList');if(!d.updates?.length)return c.innerHTML='<div class="empty"><i class="fas fa-clipboard"></i>No updates yet</div>';c.innerHTML=d.updates.map(u=>`<div class="card"><div class="card-head"><span class="card-topic">${esc(u.topic)}</span><span class="card-badge ${u.badge}">${badge(u.badge)}</span></div><div class="card-msg">${link(esc(u.message))}</div><div class="card-foot"><span class="card-author"><i class="fas fa-user"></i>${esc(u.author)}</span><span>${fmtDate(u.created_at)}</span>${user.role==='admin'?`<div class="card-actions"><button class="act-btn" onclick="editUpdate(${u.id})"><i class="fas fa-edit"></i></button><button class="act-btn del" onclick="delUpdate(${u.id})"><i class="fas fa-trash"></i></button></div>`:''}</div></div>`).join('')}
function badge(b){return{important:'🔴 Important',general:'🔵 General',info:'🟢 Info',warning:'🟡 Warning'}[b]}
function openUpdateModal(u=null){document.getElementById('updateModalTitle').textContent=u?'Edit Update':'Add Update';document.getElementById('updateId').value=u?.id||'';document.getElementById('updateTopic').value=u?.topic||'';document.getElementById('updateBadge').value=u?.badge||'general';document.getElementById('updateMsg').value=u?.message||'';openModal('updateModal')}
async function editUpdate(id){const d=await api('updates/'+id);if(d.update)openUpdateModal(d.update)}
async function delUpdate(id){if(confirm('Delete?')){await api('updates/'+id,'DELETE');loadUpdates();toast('Deleted',1)}}
async function loadLearning(){const f=await api('folders');renderFolders(f.folders||[]);const r=await api('resources'+(currentFolder?'?folder='+currentFolder:''));renderResources(r.resources||[]);document.getElementById('resFolder').innerHTML='<option value="">None</option>'+(f.folders||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}
function renderFolders(list){document.getElementById('foldersList').innerHTML=`<div class="folder ${!currentFolder?'active':''}" onclick="selFolder(null)"><i class="fas fa-layer-group"></i> All</div>`+list.map(f=>`<div class="folder ${currentFolder===f.id?'active':''}" onclick="selFolder(${f.id})"><i class="fas fa-folder"></i> ${esc(f.name)}${user.role==='admin'?`<span class="del" onclick="event.stopPropagation();delFolder(${f.id})"><i class="fas fa-times"></i></span>`:''}</div>`).join('')}
function selFolder(id){currentFolder=id;loadLearning()}
async function delFolder(id){if(confirm('Delete?')){await api('folders/'+id,'DELETE');if(currentFolder===id)currentFolder=null;loadLearning();toast('Deleted',1)}}
function renderResources(list){const c=document.getElementById('resourcesList');if(!list.length)return c.innerHTML='<div class="empty"><i class="fas fa-book"></i>No resources</div>';c.innerHTML=list.map(r=>`<div class="grid-card" onclick="openRes(${r.id},'${r.type}')"><div class="grid-icon ${r.type}"><i class="fas fa-${r.type==='pdf'?'file-pdf':'file-alt'}"></i></div><div class="grid-body"><div class="grid-title">${esc(r.topic)}</div><div class="grid-sub"><i class="fas fa-${r.type==='pdf'?'link':'align-left'}"></i> ${r.type==='pdf'?'PDF':'Text'}</div></div>${user.role==='admin'?`<div class="grid-actions" onclick="event.stopPropagation()"><button class="act-btn" onclick="editRes(${r.id})"><i class="fas fa-edit"></i></button><button class="act-btn del" onclick="delRes(${r.id})"><i class="fas fa-trash"></i></button></div>`:''}</div>`).join('')}
async function openRes(id,type){const d=await api('resources/'+id);if(!d.resource)return;if(type==='pdf')window.open(d.resource.link,'_blank');else{document.getElementById('textTitle').textContent=d.resource.topic;document.getElementById('textContent').textContent=d.resource.content;openModal('textModal')}}
function toggleResType(){const t=document.getElementById('resType').value;document.getElementById('pdfField').style.display=t==='pdf'?'block':'none';document.getElementById('textField').style.display=t==='text'?'block':'none'}
function openResourceModal(r=null){document.getElementById('resModalTitle').textContent=r?'Edit Resource':'Add Resource';document.getElementById('resId').value=r?.id||'';document.getElementById('resFolder').value=r?.folder_id||'';document.getElementById('resTopic').value=r?.topic||'';document.getElementById('resType').value=r?.type||'pdf';document.getElementById('resLink').value=r?.link||'';document.getElementById('resContent').value=r?.content||'';toggleResType();openModal('resourceModal')}
async function editRes(id){const d=await api('resources/'+id);if(d.resource)openResourceModal(d.resource)}
async function delRes(id){if(confirm('Delete?')){await api('resources/'+id,'DELETE');loadLearning();toast('Deleted',1)}}
async function loadCategories(){const d=await api('categories');renderCatDropdown(d.categories||[])}
function renderCatDropdown(list){let html=list.map(c=>`<a onclick="loadInfo(${c.id},'${esc(c.name)}')">${esc(c.name)}${user.role==='admin'?`<span class="del" onclick="event.stopPropagation();delCat(${c.id})"><i class="fas fa-times"></i></span>`:''}</a>`).join('');if(user.role==='admin')html+='<hr style="margin:5px 0"><a onclick="openCatModal()"><i class="fas fa-cog"></i> Manage</a>';document.getElementById('infoDropdown').innerHTML=html}
async function loadInfo(id,name){currentCat=id;document.getElementById('infoTitle').innerHTML='<i class="fas fa-folder-open"></i> '+esc(name);goPage('info');const d=await api('info-items?category='+id);renderInfoItems(d.items||[])}
function renderInfoItems(list){const c=document.getElementById('infoList');if(!list.length)return c.innerHTML='<div class="empty"><i class="fas fa-images"></i>No items</div>';c.innerHTML=list.map(i=>`<div class="grid-card" onclick="window.open('${esc(i.link)}','_blank')"><div class="info-img">${i.image?`<img src="${esc(i.image)}">`:'<i class="fas fa-link"></i>'}</div><div class="grid-body"><div class="grid-title">${esc(i.title)}</div><div class="grid-sub"><i class="fas fa-external-link-alt"></i> Open</div></div>${user.role==='admin'?`<div class="grid-actions" onclick="event.stopPropagation()"><button class="act-btn" onclick="editInfo(${i.id})"><i class="fas fa-edit"></i></button><button class="act-btn del" onclick="delInfo(${i.id})"><i class="fas fa-trash"></i></button></div>`:''}</div>`).join('')}
function openCatModal(){loadCatList();openModal('catModal')}
async function loadCatList(){const d=await api('categories');document.getElementById('catList').innerHTML=(d.categories||[]).map(c=>`<div class="cat-item"><span>${esc(c.name)}</span><button class="act-btn del" onclick="delCat(${c.id})"><i class="fas fa-trash"></i></button></div>`).join('')||'<p>No categories</p>'}
async function delCat(id){if(confirm('Delete?')){await api('categories/'+id,'DELETE');loadCatList();loadCategories();toast('Deleted',1)}}
function openInfoModal(i=null){document.getElementById('infoModalTitle').textContent=i?'Edit Item':'Add Item';document.getElementById('infoId').value=i?.id||'';document.getElementById('infoItemTitle').value=i?.title||'';document.getElementById('infoImage').value=i?.image||'';document.getElementById('infoLink').value=i?.link||'';openModal('infoModal')}
async function editInfo(id){const d=await api('info-items/'+id);if(d.item)openInfoModal(d.item)}
async function delInfo(id){if(confirm('Delete?')){await api('info-items/'+id,'DELETE');loadInfo(currentCat,'');toast('Deleted',1)}}
async function loadUsers(){const d=await api('users');document.getElementById('userList').innerHTML=(d.users||[]).map(u=>`<div class="user-item"><div class="user-info"><div class="user-avatar">${u.displayName[0].toUpperCase()}</div><div><div class="user-name">${esc(u.displayName)}</div><div class="user-sub">@${esc(u.username)} • ${u.role}</div></div></div>${u.username!=='admin'?`<button class="act-btn del" onclick="delUser(${u.id})"><i class="fas fa-trash"></i></button>`:''}</div>`).join('')}
async function delUser(id){if(confirm('Delete?')){await api('users/'+id,'DELETE');loadUsers();toast('Deleted',1)}}
function initForms(){document.getElementById('updateForm').onsubmit=async e=>{e.preventDefault();const id=document.getElementById('updateId').value;await api('updates'+(id?'/'+id:''),id?'PUT':'POST',{topic:document.getElementById('updateTopic').value,badge:document.getElementById('updateBadge').value,message:document.getElementById('updateMsg').value,author:user.displayName});closeModal('updateModal');loadUpdates();toast('Saved',1)};document.getElementById('folderForm').onsubmit=async e=>{e.preventDefault();await api('folders','POST',{name:document.getElementById('folderName').value});closeModal('folderModal');document.getElementById('folderName').value='';loadLearning();toast('Created',1)};document.getElementById('resourceForm').onsubmit=async e=>{e.preventDefault();const id=document.getElementById('resId').value;const type=document.getElementById('resType').value;await api('resources'+(id?'/'+id:''),id?'PUT':'POST',{folder_id:document.getElementById('resFolder').value||null,topic:document.getElementById('resTopic').value,type,link:type==='pdf'?document.getElementById('resLink').value:null,content:type==='text'?document.getElementById('resContent').value:null});closeModal('resourceModal');loadLearning();toast('Saved',1)};document.getElementById('catForm').onsubmit=async e=>{e.preventDefault();const name=document.getElementById('catName').value;if(!name)return;await api('categories','POST',{name});document.getElementById('catName').value='';loadCatList();loadCategories();toast('Added',1)};document.getElementById('infoForm').onsubmit=async e=>{e.preventDefault();const id=document.getElementById('infoId').value;await api('info-items'+(id?'/'+id:''),id?'PUT':'POST',{category_id:currentCat,title:document.getElementById('infoItemTitle').value,image:document.getElementById('infoImage').value||null,link:document.getElementById('infoLink').value});closeModal('infoModal');loadInfo(currentCat,'');toast('Saved',1)};document.getElementById('userForm').onsubmit=async e=>{e.preventDefault();await api('users','POST',{username:document.getElementById('newUser').value,password:document.getElementById('newPass').value,displayName:document.getElementById('newName').value,role:document.getElementById('newRole').value});document.getElementById('userForm').reset();loadUsers();toast('Added',1)}}
function esc(s){if(!s)return'';const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function link(s){return s.replace(/(https?:\/\/[^\s]+)/g,'<a href="$1" target="_blank">$1</a>')}
function fmtDate(d){return new Date(d).toLocaleDateString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
